[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "loaforcsSoundAPI_REPO"
description = "R.E.P.O. bindings for SoundAPI"
websiteUrl = "https://github.com/loaforcsSoundAPI/loaforcsSoundAPI.REPO"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../../README.md"
outdir = "../../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/me.loaforc.soundapi.repo.dll"
target = "BepInEx/plugins/loaforcsSoundAPI_REPO/"

[[build.copy]]
source = "../../LICENSE"
target = "LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "repo" ]
[publish.categories]
repo = [ "libraries", "mods", "tools", "audio" ]